// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameArticleDetail = "article_detail"

// ArticleDetail mapped from table <article_detail>
type ArticleDetail struct {
	ArticleDetailID int64  `gorm:"column:article_detail_id;primaryKey;autoIncrement:true" json:"article_detail_id"` // 文章详情id
	ContentMd       string `gorm:"column:content_md" json:"content_md"`                                             // 文章markdown内容
	ContentHTML     string `gorm:"column:content_html" json:"content_html"`                                         // 文章html内容
	ArticleID       string `gorm:"column:article_id" json:"article_id"`                                             // 文章id
}

// TableName ArticleDetail's table name
func (*ArticleDetail) TableName() string {
	return TableNameArticleDetail
}
