// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameArticle = "article"

// Article mapped from table <article>
type Article struct {
	ArticleID      string         `gorm:"column:article_id" json:"article_id"`           // 博文ID
	ArticleUser    string         `gorm:"column:article_user" json:"article_user"`       // 发表用户
	Title          string         `gorm:"column:title" json:"title"`                     // 博文标题
	LikeCount      int32          `gorm:"column:like_count" json:"like_count"`           // 点赞数
	CommentCount   int32          `gorm:"column:comment_count" json:"comment_count"`     // 评论数
	ReadCount      int32          `gorm:"column:read_count" json:"read_count"`           // 浏览量
	TopFlag        string         `gorm:"column:top_flag" json:"top_flag"`               // 是否置顶
	ArticleSummary string         `gorm:"column:article_summary" json:"article_summary"` // 文章摘要
	ID             int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt      time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt      time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt      gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Article's table name
func (*Article) TableName() string {
	return TableNameArticle
}
