// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameArticle = "article"

// Article mapped from table <article>
type Article struct {
	ArticleID      int64     `gorm:"column:article_id;primaryKey;autoIncrement:true" json:"article_id"` // 博文ID
	PushData       time.Time `gorm:"column:push_data" json:"push_data"`                                 // 发布日期
	ArticleUser    string    `gorm:"column:article_user" json:"article_user"`                           // 发表用户
	Title          string    `gorm:"column:title" json:"title"`                                         // 博文标题
	LikeCount      int32     `gorm:"column:like_count" json:"like_count"`                               // 点赞数
	CommentCount   int32     `gorm:"column:comment_count" json:"comment_count"`                         // 评论数
	ReadCount      int32     `gorm:"column:read_count" json:"read_count"`                               // 浏览量
	TopFlag        string    `gorm:"column:top_flag" json:"top_flag"`                                   // 是否置顶
	CreateTime     time.Time `gorm:"column:create_time" json:"create_time"`                             // 创建时间
	ArticleSummary string    `gorm:"column:article_summary" json:"article_summary"`                     // 文章摘要
}

// TableName Article's table name
func (*Article) TableName() string {
	return TableNameArticle
}
