// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCategory = "category"

// Category mapped from table <category>
type Category struct {
	ID    int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Title string `gorm:"column:title;not null" json:"title"`
}

// TableName Category's table name
func (*Category) TableName() string {
	return TableNameCategory
}
